# Generated by Django 2.0.4 on 2019-11-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('filename', models.CharField(max_length=150, verbose_name='文件名')),
                ('size', models.FloatField(verbose_name='文件大小')),
                ('md5', models.CharField(max_length=150, verbose_name='文件md5值')),
                ('mimetype', models.CharField(max_length=150, verbose_name='文件MIME类型')),
                ('is_trash', models.BooleanField(default=False, verbose_name='文件是否被删除')),
                ('type', models.IntegerField(choices=[(1, 'File'), (2, 'Directory')], verbose_name='文件类型')),
                ('addr', models.CharField(max_length=150, verbose_name='文件存储地址')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fileapp.File', verbose_name='文件父级目录')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='收藏状态')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileapp.File', verbose_name='收藏文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User', verbose_name='收藏者')),
            ],
        ),
        migrations.CreateModel(
            name='MIMEType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('token', models.CharField(max_length=150, verbose_name='分享Token')),
                ('timestamp', models.DateTimeField()),
                ('is_trash', models.IntegerField(default=1, verbose_name='是否删除分享')),
                ('password', models.CharField(blank=True, max_length=120, null=True, verbose_name='访问密码')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileapp.File', verbose_name='分享文件')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='userapp.User', verbose_name='分享者')),
                ('recv_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recv_user', to='userapp.User', verbose_name='接收分享者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('size', models.FloatField(verbose_name='节点大小')),
                ('used', models.FloatField(verbose_name='已使用大小')),
                ('path', models.CharField(max_length=150, verbose_name='存储位置')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.User', verbose_name='关联用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileapp.Storage', verbose_name='所属节点'),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User', verbose_name='关联用户'),
        ),
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('user', 'file')},
        ),
    ]
