# Generated by Django 2.0.4 on 2019-11-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='timestamp',
            field=models.CharField(max_length=128),
        ),
    ]
