# Generated by Django 2.0.4 on 2019-11-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_recently'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recently',
            old_name='user_id',
            new_name='user',
        ),
    ]
