# Generated by Django 2.0.4 on 2019-11-03 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('display_name', models.CharField(max_length=30, verbose_name='昵称')),
                ('account', models.CharField(max_length=30, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=255, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data', models.TextField(verbose_name='用户详情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User', verbose_name='关联用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
